name: macchina.io-ci
on: [push]
jobs:
  linux-gcc-make:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt install libssl-dev
      - run: make -s -j2 DEFAULT_TARGET=shared_release
