name: macchina.io-ci
on: [push]
jobs:
  ubuntu-2204-gcc-make:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update && sudo apt install libssl-dev python-is-python3
      - run: make -s -j`nproc` TESTS=1 SAMPLES=1 ASAN=1 DEFAULT_TARGET=shared_release
      - run: >-
          cp platform/Foundation/testsuite/bin/Linux/x86_64/TestApp platform/Foundation/testsuite &&
          CPPUNIT_IGNORE="
          CppUnit::TestCaller<RawSocketTest>.testEchoIPv4,
          CppUnit::TestCaller<RawSocketTest>.testSendToReceiveFromIPv4,
          CppUnit::TestCaller<ICMPClientTest>.testPing,
          CppUnit::TestCaller<ICMPClientTest>.testBigPing,
          CppUnit::TestCaller<ICMPSocketTest>.testSendToReceiveFrom,
          CppUnit::TestCaller<ICMPSocketTest>.testAssign,
          CppUnit::TestCaller<ICMPSocketTest>.testMTU,
          CppUnit::TestCaller<NTPClientTest>.testTimeSync,
          CppUnit::TestCaller<HTTPSClientSessionTest>.testProxy,
          CppUnit::TestCaller<HTTPSStreamFactoryTest>.testProxy"
          EXCLUDE_TESTS="Data/MySQL Data/ODBC Data/PostgreSQL MongoDB Redis"
          PATH=$PATH:.
          POCO_BASE=`pwd`/platform
          LD_LIBRARY_PATH=$POCO_BASE/lib/Linux/x86_64
          platform/build/script/runtests.sh

  macos-clang-make:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - run: brew install openssl@3 python@3.9
      - run: PATH=/usr/local/opt/python@3.9/libexec/bin:$PATH make -s -j`sysctl -n hw.ncpu` DEFAULT_TARGET=shared_release
